"""Add author, tag and timestamps to notes

Revision ID: 94b03ce44861
Revises: b5e8ce8b95f1
Create Date: 2025-07-03 10:36:36.639590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b03ce44861'
down_revision: Union[str, Sequence[str], None] = 'b5e8ce8b95f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
