"""Add author, tag and timestamps to notes

Revision ID: b8393467bdbc
Revises: 94b03ce44861
Create Date: 2025-07-03 10:44:39.971121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8393467bdbc'
down_revision: Union[str, Sequence[str], None] = '94b03ce44861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('tags', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'tags')
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'created_at')
    op.drop_column('notes', 'author')
    # ### end Alembic commands ###
